class CreateUserInformations < ActiveRecord::Migration[5.1]
  def change
    create_table :user_informations do |t|
      t.string :residentschoolcode
      t.string :stateid
      t.string :districtentrydate
      t.string :user_id
      t.string :suffix
      t.string :dateofbirth
      t.string :studentgradelevel
      t.string :residencystatus
      t.string :entrydate
      t.string :entrycode
      t.string :exitdate
      t.string :exitcode
      t.string :exitdestdistrictcode
      t.string :exitdestschoolcode
      t.string :exitdestcomment
      t.string :wk1att
      t.string :wk1abs
      t.string :wk1total
      t.string :wk1average
      t.string :wk2att
      t.string :wk2abs
      t.string :wk2total
      t.string :wk2average
      t.string :wk2avatt
      t.string :wk3att
      t.string :wk3abs
      t.string :wk3total
      t.string :wk3average
      t.string :wk3attav
      t.string :wk4att
      t.string :wk4abs
      t.string :wk4total
      t.string :wk4average
      t.string :wk4attav
      t.string :wk5att
      t.string :wk5abs
      t.string :wk5total
      t.string :wk5average
      t.string :wk5attav
      t.string :wk6att
      t.string :wk6abs
      t.string :wk6total
      t.string :wk6average
      t.string :wk6attav
      t.string :wk7att
      t.string :wk7abs
      t.string :wk7total
      t.string :wk7average
      t.string :wk7attav
      t.string :wk8att
      t.string :wk8abs
      t.string :wk8total
      t.string :wk8average
      t.string :wk8attav
      t.string :wk9att
      t.string :wk9abs
      t.string :wk9total
      t.string :wk9average
      t.string :wk9attav
      t.string :wk10att
      t.string :wk10abs
      t.string :wk10total
      t.string :wk10average
      t.string :wk10attav
      t.string :wk11att
      t.string :wk11abs
      t.string :wk11total
      t.string :wk11average
      t.string :wk11attav
      t.string :wk12att
      t.string :wk12abs
      t.string :wk12total
      t.string :wk12average
      t.string :wk12attav
      t.string :wk13att
      t.string :wk13abs
      t.string :wk13total
      t.string :wk13average
      t.string :wk13attav
      t.string :wk14att
      t.string :wk14abs
      t.string :wk14total
      t.string :wk14average
      t.string :wk14attav
      t.string :wk15att
      t.string :wk15abs
      t.string :wk15total
      t.string :wk15average
      t.string :wk15attav
      t.string :wk16att
      t.string :wk16abs
      t.string :wk16total
      t.string :wk16average
      t.string :wk16attav
      t.string :wk17att
      t.string :wk17abs
      t.string :wk17total
      t.string :wk17average
      t.string :wk17attav
      t.string :wk18att
      t.string :wk18abs
      t.string :wk18total
      t.string :wk18average
      t.string :wk18attav
      t.string :wk19att
      t.string :wk19abs
      t.string :wk19total
      t.string :wk19average
      t.string :wk19attav
      t.string :wk20att
      t.string :wk20abs
      t.string :wk20total
      t.string :wk20average
      t.string :wk20attav
      t.string :wk21att
      t.string :wk21abs
      t.string :wk21total
      t.string :wk21average
      t.string :wk21attav
      t.string :wk22att
      t.string :wk22abs
      t.string :wk22total
      t.string :wk22average
      t.string :wk22attav
      t.string :wk23att
      t.string :wk23abs
      t.string :wk23total
      t.string :wk23average
      t.string :wk23attav
      t.string :wk24att
      t.string :wk24abs
      t.string :wk24total
      t.string :wk24average
      t.string :wk24attav
      t.string :wk25att
      t.string :wk25abs
      t.string :wk25total
      t.string :wk25average
      t.string :wk25attav
      t.string :wk26att
      t.string :wk26abs
      t.string :wk26total
      t.string :wk26average
      t.string :wk26attav
      t.string :wk27att
      t.string :wk27abs
      t.string :wk27total
      t.string :wk27average
      t.string :wk27attav
      t.string :wk28att
      t.string :wk28abs
      t.string :wk28total
      t.string :wk28average
      t.string :wk28attav
      t.string :wk29att
      t.string :wk29abs
      t.string :wk29total
      t.string :wk29average
      t.string :wk29attav
      t.string :wk30att
      t.string :wk30abs
      t.string :wk30total
      t.string :wk30average
      t.string :wk30attav

      t.timestamps
    end
  end
end
